'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { Disc, Shield, Plus, CheckCircle2, ArrowRight, MapPin, Clock } from 'lucide-react';
import TopUtilityRibbon from '@/components/TopUtilityRibbon';
import MainHeader from '@/components/MainHeader';
import Footer from '@/components/Footer';
import WhatsAppFloatingButton from '@/components/WhatsAppFloatingButton';
import { SKUS, PATTERNS } from '@/data/mockData';
import { useApp } from '@/context/AppContext';

export default function BusTyresPage() {
  const { session, addToCart } = useApp();
  const [quantities, setQuantities] = useState<Record<string, number>>({});

  const busSkus = SKUS.filter((s) => s.category === 'bus');

  const handleQtyChange = (skuId: string, delta: number) => {
    setQuantities((prev) => {
      const current = prev[skuId] || 4;
      return { ...prev, [skuId]: Math.max(1, current + delta) };
    });
  };

  return (
    <div className="min-h-screen flex flex-col bg-[#121416]">
      <TopUtilityRibbon />
      <MainHeader />

      <main className="flex-1">
        {/* Hero */}
        <section className="bg-[#1C1F22] border-b border-[#25292E] py-12 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded bg-amber-500/20 text-amber-400 text-xs font-condensed font-bold uppercase tracking-wider mb-3">
              <Disc className="w-4 h-4" />
              <span>Public Transit &amp; Commercial Coach Solutions</span>
            </div>

            <h1 className="font-condensed font-black text-4xl sm:text-5xl text-white uppercase tracking-tight">
              COMMERCIAL BUS &amp; COACH TYRES
            </h1>
            <p className="text-sm sm:text-base text-[#CED4DA] max-w-2xl mt-2 leading-relaxed">
              Engineered specifically for metro city bus networks, school bus operators, and long-distance passenger coaches. Built with heavy reinforced kerb-guard sidewalls and low-noise ride comfort.
            </p>
          </div>
        </section>

        {/* Bus Special Features */}
        <section className="py-8 px-4 bg-[#16181B] border-b border-[#25292E]">
          <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-[#1C1F22] p-5 rounded-xl border border-[#2B3036]">
              <div className="font-condensed font-bold text-lg text-white uppercase">
                Reinforced Kerb Guards
              </div>
              <p className="text-xs text-[#868E96] mt-1">
                Sacrificial rubber sidewall ribs protect the casing belt package against repetitive passenger boarding curb scuffing.
              </p>
            </div>

            <div className="bg-[#1C1F22] p-5 rounded-xl border border-[#2B3036]">
              <div className="font-condensed font-bold text-lg text-white uppercase">
                Stop-and-Go Thermal Resistance
              </div>
              <p className="text-xs text-[#868E96] mt-1">
                Specially formulated bead compounds resist intense thermal transfer generated by frequent city bus disc brake cycles.
              </p>
            </div>

            <div className="bg-[#1C1F22] p-5 rounded-xl border border-[#2B3036]">
              <div className="font-condensed font-bold text-lg text-white uppercase">
                Acoustic Multi-Pitch Grooves
              </div>
              <p className="text-xs text-[#868E96] mt-1">
                Computer-sequenced tread pattern minimizes road resonance in bus cabins for superior passenger comfort.
              </p>
            </div>
          </div>
        </section>

        {/* Bus SKUs Grid */}
        <section className="py-12 px-4">
          <div className="max-w-7xl mx-auto">
            <h2 className="font-condensed font-black text-2xl text-white uppercase mb-6">
              Bus Tyre Configurations
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {busSkus.map((sku) => {
                const currentQty = quantities[sku.id] || 4;
                const totalStock =
                  sku.inStockBranches.rocklea +
                  sku.inStockBranches.yatala +
                  sku.inStockBranches.baldhills;

                return (
                  <div
                    key={sku.id}
                    className="bg-[#1C1F22] border border-[#2B3036] rounded-xl overflow-hidden flex flex-col justify-between hover:border-[#D50000] transition"
                  >
                    <div className="p-5">
                      <div className="flex items-center justify-between mb-3">
                        <span className="font-condensed font-black text-lg text-white">
                          {sku.brandName}
                        </span>
                        <span className="text-[10px] bg-[#D50000] text-white px-2 py-0.5 rounded font-bold uppercase">
                          Transit Rated
                        </span>
                      </div>

                      <div className="font-mono font-black text-2xl text-white">
                        {sku.size}
                      </div>
                      <div className="text-xs font-mono text-[#868E96] mt-0.5">
                        {sku.fullSizeCode}
                      </div>

                      <div className="grid grid-cols-3 gap-2 mt-4 text-[11px] text-center">
                        <div className="bg-[#121416] p-2 rounded border border-[#2B3036]">
                          <div className="text-[#868E96]">Tread Depth</div>
                          <div className="font-mono font-bold text-white text-xs mt-0.5">
                            {sku.treadDepthMm} mm
                          </div>
                        </div>
                        <div className="bg-[#121416] p-2 rounded border border-[#2B3036]">
                          <div className="text-[#868E96]">Ply Rating</div>
                          <div className="font-mono font-bold text-white text-xs mt-0.5">
                            {sku.plyRating}
                          </div>
                        </div>
                        <div className="bg-[#121416] p-2 rounded border border-[#2B3036]">
                          <div className="text-[#868E96]">Load / Speed</div>
                          <div className="font-mono font-bold text-white text-xs mt-0.5">
                            {sku.loadIndexSingle}/{sku.loadIndexDual}{sku.speedSymbol}
                          </div>
                        </div>
                      </div>

                      <div className="mt-4 pt-3 border-t border-[#25292E] text-xs">
                        <div className="flex justify-between text-[#CED4DA]">
                          <span className="text-[#868E96]">Stock Availability:</span>
                          <span className="text-emerald-400 font-bold">In Stock ({totalStock} units)</span>
                        </div>
                      </div>
                    </div>

                    <div className="p-5 pt-0">
                      <div className="pt-3 border-t border-[#25292E] flex items-center gap-2">
                        {session ? (
                          <>
                            <div className="flex items-center bg-[#121416] border border-[#343A40] rounded-lg">
                              <button
                                onClick={() => handleQtyChange(sku.id, -2)}
                                className="w-10 h-10 flex items-center justify-center text-white hover:bg-[#25292E] text-base font-bold"
                              >
                                -
                              </button>
                              <span className="w-10 text-center font-mono font-bold text-white text-sm">
                                {currentQty}
                              </span>
                              <button
                                onClick={() => handleQtyChange(sku.id, 2)}
                                className="w-10 h-10 flex items-center justify-center text-white hover:bg-[#25292E] text-base font-bold"
                              >
                                +
                              </button>
                            </div>

                            <button
                              onClick={() => addToCart(sku, currentQty)}
                              className="flex-1 h-10 bg-[#D50000] hover:bg-[#B30000] text-white rounded-lg font-condensed font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition"
                            >
                              <Plus className="w-4 h-4" />
                              <span>Add to RFQ</span>
                            </button>
                          </>
                        ) : (
                          <Link
                            href="/dealer/login"
                            className="w-full h-10 bg-[#25292E] hover:bg-[#D50000] text-white rounded-lg font-condensed font-bold text-xs uppercase tracking-wider flex items-center justify-center"
                          >
                            <span>Dealer Login for Pricing</span>
                          </Link>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      </main>

      <Footer />
      <WhatsAppFloatingButton />
    </div>
  );
}
